# Generated by Django 5.2.17 on 2026-09-08 09:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0008_document_material_override_and_more'),
        ('facts', '0002_clinicalreportrevision_clinicalreportspan_and_more'),
        ('patients', '0006_patientshare_sharesource_shareviewergrant_and_more'),
        ('processing', '0005_materialdecision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancerCandidate',
            fields=[
                ('revision_number', models.PositiveIntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurrence_key', models.CharField(max_length=64)),
                ('rule_version', models.CharField(max_length=64)),
                ('original_data', models.JSONField()),
                ('original_source', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancer_candidates', to='documents.document')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancer_candidates', to='patients.patient')),
                ('source_fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancer_candidates', to='facts.fact')),
                ('source_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancer_candidates', to='facts.clinicalreport')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CandidateRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('action', models.CharField(max_length=16)),
                ('before', models.JSONField()),
                ('after', models.JSONField()),
                ('reason', models.TextField(blank=True, max_length=1000)),
                ('checked_original', models.BooleanField(default=False)),
                ('source_token', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='cancer_ordering.cancercandidate')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='CollectionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_key', models.CharField(max_length=64)),
                ('sequence', models.PositiveIntegerField()),
                ('rule_version', models.CharField(max_length=64)),
                ('input_fingerprint', models.CharField(max_length=64)),
                ('input_snapshot', models.JSONField()),
                ('status', models.CharField(choices=[('COMPLETE', '收集完成'), ('FAILED', '收集失败')], max_length=12)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('candidate_count', models.PositiveIntegerField(default=0)),
                ('author_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancer_collections', to='documents.document')),
                ('parsing_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processing.parsingversion')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancer_collections', to='patients.patient')),
                ('source_fact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facts.fact')),
            ],
            options={
                'ordering': ['scope_key', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='CollectionCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='cancer_ordering.cancercandidate')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='cancer_ordering.collectionrun')),
            ],
            options={
                'ordering': ['ordinal'],
            },
        ),
        migrations.CreateModel(
            name='DisplaySelection',
            fields=[
                ('revision_number', models.PositiveIntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancer_display_selection', to='patients.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SelectionRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('SELECT', '选择显示顺序'), ('UNDO', '撤销选择')], max_length=16)),
                ('before', models.JSONField()),
                ('after', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cancer_ordering.cancercandidate')),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='cancer_ordering.displayselection')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='cancercandidate',
            index=models.Index(fields=['patient', 'document'], name='cancer_patient_document'),
        ),
        migrations.AddConstraint(
            model_name='cancercandidate',
            constraint=models.UniqueConstraint(fields=('source_fact', 'occurrence_key'), name='cancer_candidate_occurrence'),
        ),
        migrations.AddConstraint(
            model_name='candidaterevision',
            constraint=models.UniqueConstraint(fields=('candidate', 'sequence'), name='cancer_revision_sequence'),
        ),
        migrations.AddConstraint(
            model_name='collectionrun',
            constraint=models.UniqueConstraint(fields=('patient', 'scope_key', 'sequence'), name='cancer_collection_sequence'),
        ),
        migrations.AddConstraint(
            model_name='collectionrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('parsing_version__isnull', False), ('source_fact__isnull', True)), models.Q(('parsing_version__isnull', True), ('source_fact__isnull', False)), _connector='OR'), name='cancer_collection_scope'),
        ),
        migrations.AddConstraint(
            model_name='collectioncandidate',
            constraint=models.UniqueConstraint(fields=('collection', 'candidate'), name='cancer_collection_candidate'),
        ),
        migrations.AddConstraint(
            model_name='collectioncandidate',
            constraint=models.UniqueConstraint(fields=('collection', 'ordinal'), name='cancer_collection_ordinal'),
        ),
        migrations.AddConstraint(
            model_name='selectionrevision',
            constraint=models.UniqueConstraint(fields=('selection', 'sequence'), name='cancer_selection_sequence'),
        ),
    ]
