# Generated by Django 5.2.17 on 2026-09-08 18:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_ordering', '0001_initial'),
        ('documents', '0008_document_material_override_and_more'),
        ('facts', '0002_clinicalreportrevision_clinicalreportspan_and_more'),
        ('patients', '0006_patientshare_sharesource_shareviewergrant_and_more'),
        ('processing', '0005_materialdecision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancercandidate',
            name='source_fact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancer_candidates', to='facts.fact'),
        ),
        migrations.CreateModel(
            name='NarrativeSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_key', models.CharField(max_length=64, unique=True)),
                ('occurrence_key', models.CharField(db_index=True, max_length=64)),
                ('rule_version', models.CharField(max_length=64)),
                ('role', models.CharField(max_length=32)),
                ('raw_text', models.TextField()),
                ('original_data', models.JSONField()),
                ('original_source', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancer_narratives', to='documents.document')),
                ('document_page', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='documents.documentpage')),
                ('parsing_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processing.parsingversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NarrativeDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_fact_id', models.UUIDField()),
                ('original_ranges', models.JSONField(blank=True, default=list)),
                ('position_status', models.CharField(max_length=16)),
                ('input_snapshot', models.JSONField()),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narrative_dependencies', to='cancer_ordering.collectionrun')),
                ('fact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancer_narrative_dependencies', to='facts.fact')),
                ('narrative_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='cancer_ordering.narrativesource')),
            ],
        ),
        migrations.AddField(
            model_name='cancercandidate',
            name='source_narrative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='cancer_ordering.narrativesource'),
        ),
        migrations.AddField(
            model_name='collectioncandidate',
            name='narrative_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cancer_ordering.narrativesource'),
        ),
        migrations.AddConstraint(
            model_name='cancercandidate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_fact__isnull', False), ('source_narrative__isnull', True)), models.Q(('source_fact__isnull', True), ('source_narrative__isnull', False), ('source_report__isnull', True)), _connector='OR'), name='cancer_candidate_source_xor'),
        ),
        migrations.AddConstraint(
            model_name='cancercandidate',
            constraint=models.UniqueConstraint(condition=models.Q(('source_narrative__isnull', False)), fields=('document', 'occurrence_key'), name='cancer_narrative_occurrence'),
        ),
        migrations.AddConstraint(
            model_name='narrativedependency',
            constraint=models.UniqueConstraint(fields=('collection', 'narrative_source', 'original_fact_id'), name='cancer_narrative_parent'),
        ),
    ]
