# Generated by Django 5.2.17 on 2026-09-10 15:43

import django.db.models.deletion
import hashlib
import json
import uuid
from django.conf import settings
from django.db import migrations, models


def preserve_reviews(apps, schema_editor):
    """Read stored snapshots only; never extract, scan OCR or alter old rows."""
    Candidate = apps.get_model('cancer_ordering', 'CancerCandidate')
    Review = apps.get_model('cancer_ordering', 'OccurrenceReview')
    database = schema_editor.connection.alias
    for candidate in Candidate.objects.using(database).select_related('source_fact', 'source_narrative').iterator():
        source = candidate.source_narrative if candidate.source_narrative_id else candidate.source_fact
        version_id = source.parsing_version_id if source else None
        fragments = candidate.original_source.get('label_fragments', [])
        exact = bool(fragments) and all(item.get('block_id') and type(item.get('start')) is int for item in fragments)
        if exact:
            positions = [[item['page_id'], item['block_id'], item['start'] + index]
                         for item in fragments for index, char in enumerate(item['raw']) if not char.isspace()]
            material = {'version_id': str(version_id), 'positions': positions}
        else:
            material = {'version_id': str(version_id) if version_id else None,
                        'unlocated_pages': sorted({str(item['page_id']) for item in fragments if item.get('page_id')})}
        key = hashlib.sha256(json.dumps(material,
            ensure_ascii=False, sort_keys=True, separators=(',', ':'), default=str).encode('utf-8')).hexdigest()
        for revision in candidate.revisions.using(database).order_by('sequence').iterator():
            Review.objects.using(database).create(document_id=candidate.document_id, parsing_version_id=version_id,
                position_key=key, candidate_id=candidate.pk, original_candidate_id=candidate.pk,
                original_revision_id=revision.pk, author_id=revision.author_id, action=revision.action,
                before=revision.before, after=revision.after, original_source=candidate.original_source,
                reviewed_at=revision.created_at)


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_ordering', '0002_narrative_sources'),
        ('documents', '0008_document_material_override_and_more'),
        ('processing', '0005_materialdecision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OccurrenceReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position_key', models.CharField(db_index=True, max_length=64)),
                ('original_candidate_id', models.UUIDField()),
                ('original_revision_id', models.UUIDField(unique=True)),
                ('action', models.CharField(max_length=16)),
                ('before', models.JSONField()),
                ('after', models.JSONField()),
                ('original_source', models.JSONField()),
                ('reviewed_at', models.DateTimeField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cancer_ordering.cancercandidate')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
                ('parsing_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processing.parsingversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(preserve_reviews, migrations.RunPython.noop),
    ]
