# Generated by Django 5.2.17 on 2026-08-30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtpChallenge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phone_hash", models.CharField(db_index=True, max_length=64)),
                ("phone_encrypted", models.TextField()),
                ("ip_hash", models.CharField(db_index=True, max_length=64)),
                ("otp_hash", models.CharField(blank=True, max_length=256)),
                ("delivery_status", models.CharField(choices=[("pending", "Pending"), ("sent", "Sent"), ("failed", "Failed")], default="pending", max_length=8)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("expires_at", models.DateTimeField()),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["phone_hash", "created_at"], name="accounts_ot_phone_h_7debe1_idx"),
                    models.Index(fields=["ip_hash", "created_at"], name="accounts_ot_ip_hash_6e5a6f_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="OtpThrottle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scope", models.CharField(max_length=5)),
                ("identifier_hash", models.CharField(max_length=64)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("scope", "identifier_hash"), name="unique_otp_throttle"),
                ],
            },
        ),
    ]
