# Generated by Django 5.2.17 on 2026-08-31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_consent_record"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountDeletionJob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deletion_job",
                        to="accounts.account",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="accountdeletionjob",
            index=models.Index(fields=["next_attempt_at", "created_at"], name="accounts_deletion_due"),
        ),
    ]
