# Generated by Django 5.2.17 on 2026-08-31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_accountdeletionjob"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountSession",
            fields=[
                ("session_key", models.CharField(max_length=40, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registered_sessions",
                        to="accounts.account",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="accountsession",
            index=models.Index(fields=["account", "-last_seen_at"], name="accounts_session_account"),
        ),
    ]
