# Generated by Django 5.2.17 on 2026-08-31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_accountsession"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="otpchallenge",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("sign_in", "Sign in"),
                    ("first_use", "First use"),
                    ("password_reset", "Password reset"),
                ],
                default="first_use",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="otpchallenge",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="otp_challenges",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="PasswordAttemptThrottle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scope", models.CharField(max_length=5)),
                ("identifier_hash", models.CharField(max_length=64)),
                ("window_started_at", models.DateTimeField()),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scope", "identifier_hash"),
                        name="unique_password_attempt_throttle",
                    )
                ],
            },
        ),
    ]
