# Generated by Django 5.2.17 on 2026-09-07 22:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0008_document_material_override_and_more'),
        ('exports', '0002_exportjob_access_revision_exportjob_requested_by'),
        ('labs', '0004_alter_labobservation_raw_value_and_more'),
        ('patients', '0006_patientshare_sharesource_shareviewergrant_and_more'),
        ('processing', '0005_materialdecision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlucoseRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_key', models.UUIDField()),
                ('creation_fingerprint', models.CharField(max_length=64)),
                ('original_data', models.JSONField()),
                ('current_data', models.JSONField()),
                ('source_kind', models.CharField(choices=[('LAB_REPORT', '检验单'), ('NURSING', '护理原件核对录入'), ('METER', '血糖仪自测'), ('MANUAL', '手动记录')], max_length=16)),
                ('source_fingerprint', models.CharField(blank=True, max_length=64)),
                ('measured_at', models.DateTimeField(blank=True, null=True)),
                ('measured_date', models.DateField(blank=True, null=True)),
                ('time_precision', models.CharField(max_length=10)),
                ('revision_number', models.PositiveIntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_glucose_records', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glucose_records', to='patients.patient')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='glucose_records', to='documents.document')),
                ('source_observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='glucose_records', to='labs.labobservation')),
                ('source_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='glucose_records', to='documents.documentpage')),
                ('source_parsing_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='glucose_records', to='processing.parsingversion')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_glucose_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-measured_date', '-measured_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GlucoseExportSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glucose_sources', to='exports.exportjob')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_bindings', to='glucose.glucoserecord')),
            ],
        ),
        migrations.CreateModel(
            name='GlucoseRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('CORRECT', '更正'), ('DELETE', '删除'), ('UNDO', '撤销'), ('RECHECK', '来源重核')], max_length=16)),
                ('before', models.JSONField()),
                ('after', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='glucose.glucoserecord')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='GlucoseShareSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_bindings', to='glucose.glucoserecord')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glucose_sources', to='patients.patientshare')),
            ],
        ),
        migrations.AddIndex(
            model_name='glucoserecord',
            index=models.Index(fields=['patient', 'deleted_at', '-measured_date'], name='glucose_patient_date'),
        ),
        migrations.AddConstraint(
            model_name='glucoserecord',
            constraint=models.UniqueConstraint(fields=('patient', 'created_by', 'creation_key'), name='glucose_creation_unique'),
        ),
        migrations.AddConstraint(
            model_name='glucoserecord',
            constraint=models.UniqueConstraint(fields=('patient', 'source_observation'), name='glucose_observation_unique'),
        ),
        migrations.AddConstraint(
            model_name='glucoseexportsource',
            constraint=models.UniqueConstraint(fields=('job', 'record'), name='glucose_export_unique'),
        ),
        migrations.AddConstraint(
            model_name='glucoserevision',
            constraint=models.UniqueConstraint(fields=('record', 'sequence'), name='glucose_revision_unique'),
        ),
        migrations.AddConstraint(
            model_name='glucosesharesource',
            constraint=models.UniqueConstraint(fields=('share', 'record'), name='glucose_share_unique'),
        ),
    ]
