import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadBatch",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("file_count", models.PositiveSmallIntegerField(default=0)),
                ("page_count", models.PositiveSmallIntegerField(default=0)),
                ("byte_size", models.BigIntegerField(default=0)),
                ("status", models.CharField(choices=[("ACTIVE", "Active"), ("COMPLETED", "Completed")], default="ACTIVE", max_length=12)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("patient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="upload_batches", to="patients.patient")),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("display_filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("byte_size", models.BigIntegerField()),
                ("page_count", models.PositiveSmallIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("perceptual_hash", models.CharField(blank=True, max_length=128)),
                ("original_object_key", models.CharField(max_length=512, unique=True)),
                ("status", models.CharField(choices=[("PROCESSING", "处理中"), ("ORGANIZED", "已整理"), ("ORIGINAL_ONLY", "仅原件"), ("PROCESSING_FAILED", "处理失败")], default="PROCESSING", max_length=24)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("purged_at", models.DateTimeField(blank=True, null=True)),
                ("batch", models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name="documents", to="documents.uploadbatch")),
                ("patient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="documents", to="patients.patient")),
            ],
        ),
        migrations.CreateModel(
            name="UploadItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("ordinal", models.PositiveSmallIntegerField()),
                ("display_filename", models.CharField(max_length=255)),
                ("byte_size", models.BigIntegerField(default=0)),
                ("page_count", models.PositiveSmallIntegerField(default=0)),
                ("status", models.CharField(choices=[("PENDING", "待上传"), ("UPLOADING", "上传中"), ("UPLOAD_FAILED", "上传失败"), ("CREATED", "处理中"), ("EXACT_DUPLICATE", "已存在")], default="PENDING", max_length=20)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("batch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="documents.uploadbatch")),
                ("document", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name="upload_items", to="documents.document")),
            ],
        ),
        migrations.CreateModel(
            name="DocumentPage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("page_number", models.PositiveSmallIntegerField()),
                ("image_object_key", models.CharField(blank=True, max_length=512, null=True)),
                ("text_object_key", models.CharField(blank=True, max_length=512, null=True)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("orientation", models.CharField(blank=True, choices=[("PORTRAIT", "Portrait"), ("LANDSCAPE", "Landscape"), ("SQUARE", "Square")], max_length=10)),
                ("document", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pages", to="documents.document")),
            ],
        ),
        migrations.CreateModel(
            name="PatientUploadQuota",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("batch_file_limit", models.PositiveSmallIntegerField(default=20)),
                ("batch_page_limit", models.PositiveSmallIntegerField(default=60)),
                ("document_limit", models.PositiveSmallIntegerField(default=300)),
                ("page_limit", models.PositiveIntegerField(default=1000)),
                ("storage_byte_limit", models.BigIntegerField(default=2147483648)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("patient", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="upload_quota", to="patients.patient")),
            ],
        ),
        migrations.CreateModel(
            name="ProcessingRun",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("parser_version", models.CharField(max_length=64)),
                ("task_type", models.CharField(max_length=64)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("attempt_number", models.PositiveSmallIntegerField(default=1)),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("stage", models.CharField(choices=[("QUEUED", "Queued"), ("PREPARING", "Preparing"), ("OCR", "OCR"), ("CLASSIFYING", "Classifying"), ("EXTRACTING", "Extracting"), ("INDEXING", "Indexing"), ("SUCCEEDED", "Succeeded"), ("NO_STRUCTURED_RESULT", "No structured result"), ("FAILED", "Failed")], default="QUEUED", max_length=24)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("document", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="processing_runs", to="documents.document")),
            ],
        ),
        migrations.AddIndex(model_name="uploadbatch", index=models.Index(fields=["patient", "-created_at"], name="documents_batch_patient_recent")),
        migrations.AddIndex(model_name="uploadbatch", index=models.Index(fields=["patient", "status", "completed_at"], name="documents_batch_task_cards")),
        migrations.AddConstraint(model_name="uploadbatch", constraint=models.CheckConstraint(condition=models.Q(("file_count__lte", 20)), name="documents_batch_files_max")),
        migrations.AddConstraint(model_name="uploadbatch", constraint=models.CheckConstraint(condition=models.Q(("page_count__lte", 60)), name="documents_batch_pages_max")),
        migrations.AddConstraint(model_name="uploadbatch", constraint=models.CheckConstraint(condition=models.Q(("byte_size__gte", 0)), name="documents_batch_bytes_nonnegative")),
        migrations.AddConstraint(model_name="uploadbatch", constraint=models.CheckConstraint(condition=models.Q(models.Q(("completed_at__isnull", True), ("status", "ACTIVE")), models.Q(("completed_at__isnull", False), ("status", "COMPLETED")), _connector="OR"), name="documents_batch_completion_consistent")),
        migrations.AddIndex(model_name="document", index=models.Index(fields=["patient", "deleted_at", "-created_at"], name="docs_patient_active_recent")),
        migrations.AddIndex(model_name="document", index=models.Index(fields=["patient", "status", "-created_at"], name="docs_patient_status_recent")),
        migrations.AddConstraint(model_name="document", constraint=models.CheckConstraint(condition=models.Q(("byte_size__gt", 0)), name="documents_bytes_positive")),
        migrations.AddConstraint(model_name="document", constraint=models.CheckConstraint(condition=models.Q(("page_count__gt", 0)), name="documents_pages_positive")),
        migrations.AddConstraint(model_name="document", constraint=models.CheckConstraint(condition=~models.Q(("original_object_key", "")), name="documents_object_key_present")),
        migrations.AddConstraint(model_name="document", constraint=models.CheckConstraint(condition=models.Q(("purged_at__isnull", True), models.Q(("deleted_at__isnull", False), ("purged_at__gte", models.F("deleted_at"))), _connector="OR"), name="documents_purge_after_delete")),
        migrations.AddConstraint(model_name="document", constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("patient", "sha256"), name="documents_active_patient_sha256")),
        migrations.AddIndex(model_name="uploaditem", index=models.Index(fields=["batch", "status"], name="documents_item_batch_status")),
        migrations.AddIndex(model_name="uploaditem", index=models.Index(fields=["status", "-created_at"], name="documents_item_status_recent")),
        migrations.AddConstraint(model_name="uploaditem", constraint=models.UniqueConstraint(fields=("batch", "ordinal"), name="documents_item_batch_ordinal")),
        migrations.AddConstraint(model_name="uploaditem", constraint=models.CheckConstraint(condition=models.Q(("ordinal__gt", 0)), name="documents_item_ordinal_positive")),
        migrations.AddConstraint(model_name="uploaditem", constraint=models.CheckConstraint(condition=models.Q(("byte_size__gte", 0)), name="documents_item_bytes_nonnegative")),
        migrations.AddConstraint(model_name="uploaditem", constraint=models.CheckConstraint(condition=models.Q(models.Q(("document__isnull", True), ("status__in", ["PENDING", "UPLOADING", "UPLOAD_FAILED"])), models.Q(("document__isnull", False), ("status__in", ["CREATED", "EXACT_DUPLICATE"])), _connector="OR"), name="documents_item_result_document")),
        migrations.AddConstraint(model_name="uploaditem", constraint=models.CheckConstraint(condition=(models.Q(("status", "UPLOAD_FAILED")) & ~models.Q(("error_code", ""))) | (models.Q(("status__in", ["PENDING", "UPLOADING", "CREATED", "EXACT_DUPLICATE"])) & models.Q(("error_code", ""))), name="documents_item_error_code_consistent")),
        migrations.AddConstraint(model_name="uploaditem", constraint=models.UniqueConstraint(condition=models.Q(("status", "CREATED")), fields=("document",), name="documents_one_created_item_document")),
        migrations.AddConstraint(model_name="documentpage", constraint=models.UniqueConstraint(fields=("document", "page_number"), name="documents_page_document_number")),
        migrations.AddConstraint(model_name="documentpage", constraint=models.CheckConstraint(condition=models.Q(("page_number__gt", 0)), name="documents_page_number_positive")),
        migrations.AddConstraint(model_name="documentpage", constraint=models.CheckConstraint(condition=models.Q(models.Q(("height__isnull", True), ("width__isnull", True)), models.Q(("width__gt", 0), ("height__gt", 0)), _connector="OR"), name="documents_page_dimensions_valid")),
        migrations.AddConstraint(model_name="patientuploadquota", constraint=models.CheckConstraint(condition=models.Q(("batch_file_limit__gt", 0)), name="documents_quota_batch_files_positive")),
        migrations.AddConstraint(model_name="patientuploadquota", constraint=models.CheckConstraint(condition=models.Q(("batch_file_limit__lte", 20)), name="documents_quota_batch_files_cap")),
        migrations.AddConstraint(model_name="patientuploadquota", constraint=models.CheckConstraint(condition=models.Q(("batch_page_limit__gt", 0)), name="documents_quota_batch_pages_positive")),
        migrations.AddConstraint(model_name="patientuploadquota", constraint=models.CheckConstraint(condition=models.Q(("batch_page_limit__lte", 60)), name="documents_quota_batch_pages_cap")),
        migrations.AddConstraint(model_name="patientuploadquota", constraint=models.CheckConstraint(condition=models.Q(("document_limit__gt", 0)), name="documents_quota_documents_positive")),
        migrations.AddConstraint(model_name="patientuploadquota", constraint=models.CheckConstraint(condition=models.Q(("page_limit__gt", 0)), name="documents_quota_pages_positive")),
        migrations.AddConstraint(model_name="patientuploadquota", constraint=models.CheckConstraint(condition=models.Q(("storage_byte_limit__gt", 0)), name="documents_quota_bytes_positive")),
        migrations.AddIndex(model_name="processingrun", index=models.Index(fields=["stage", "heartbeat_at"], name="documents_run_stale_recovery")),
        migrations.AddIndex(model_name="processingrun", index=models.Index(fields=["document", "is_current"], name="documents_run_document_current")),
        migrations.AddConstraint(model_name="processingrun", constraint=models.UniqueConstraint(condition=models.Q(("is_current", True)), fields=("document",), name="documents_one_current_run")),
        migrations.AddConstraint(model_name="processingrun", constraint=models.CheckConstraint(condition=models.Q(("is_current", False)) | (models.Q(("stage__in", ["SUCCEEDED", "NO_STRUCTURED_RESULT"])) & models.Q(("finished_at__isnull", False))), name="documents_current_run_terminal")),
        migrations.AddConstraint(model_name="processingrun", constraint=models.CheckConstraint(condition=models.Q(models.Q(("finished_at__isnull", False), ("stage__in", ["SUCCEEDED", "NO_STRUCTURED_RESULT", "FAILED"])), models.Q(("finished_at__isnull", True), ("stage__in", ["QUEUED", "PREPARING", "OCR", "CLASSIFYING", "EXTRACTING", "INDEXING"])), _connector="OR"), name="documents_run_terminal_finished")),
        migrations.AddConstraint(model_name="processingrun", constraint=models.UniqueConstraint(condition=models.Q(("stage__in", ["QUEUED", "PREPARING", "OCR", "CLASSIFYING", "EXTRACTING", "INDEXING"])), fields=("document",), name="documents_one_nonterminal_run")),
        migrations.AddConstraint(model_name="processingrun", constraint=models.CheckConstraint(condition=models.Q(("attempt_number__gt", 0)), name="documents_run_attempt_positive")),
    ]
