# Generated by Django 5.2.17 on 2026-08-31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_processingrun_lease_token"),
        ("processing", "0002_documentsummary"),
    ]

    operations = [
        migrations.CreateModel(
            name="InaccuracyFeedback",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("category", models.CharField(default="DOCUMENT_RECOGNITION", max_length=32)),
                ("idempotency_key", models.CharField(max_length=160, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inaccuracy_feedback",
                        to="documents.document",
                    ),
                ),
                (
                    "parsing_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inaccuracy_feedback",
                        to="processing.parsingversion",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="inaccuracyfeedback",
            index=models.Index(fields=["document", "-created_at"], name="documents_feedback_recent"),
        ),
    ]
