# Generated by Django 5.2.17 on 2026-08-31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_inaccuracyfeedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentDeletionJob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("object_key", models.CharField(max_length=512)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deletion_job",
                        to="documents.document",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="documentdeletionjob",
            index=models.Index(fields=["next_attempt_at", "created_at"], name="documents_deletion_due"),
        ),
    ]
