# Generated by Django 5.2.17 on 2026-09-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_documentdeletionjob'),
        ('patients', '0002_patientpreference_productfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='lifecycle_revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='trash_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='trashed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['trash_expires_at'], name='documents_trash_expiry'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('trash_expires_at__isnull', True), ('trashed_at__isnull', True)), models.Q(('deleted_at', models.F('trashed_at')), ('purged_at__isnull', True), ('trash_expires_at__gt', models.F('trashed_at')), ('trashed_at__isnull', False)), _connector='OR'), name='documents_trash_state_consistent'),
        ),
    ]
