# Generated by Django 5.2.17 on 2026-09-07 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_created_by_uploadbatch_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processingrun',
            name='access_revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processingrun',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
