# Generated by Django 5.2.17 on 2026-09-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_processingrun_access_revision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='material_override',
            field=models.CharField(choices=[('AUTO', '自动判断'), ('KEEP_DOCUMENT', '按资料保留')], default='AUTO', max_length=16),
        ),
        migrations.AddField(
            model_name='document',
            name='material_revision',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
