# Generated by Django 5.2.17 on 2026-09-17 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_document_material_override_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadIntake',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='intake', serialize=False, to='documents.uploaditem')),
                ('state', models.CharField(choices=[('QUEUED', 'QUEUED'), ('RECOGNIZING', 'RECOGNIZING'), ('READY', 'READY'), ('SETTLED', 'SETTLED')], default='QUEUED', max_length=16)),
                ('staged', models.JSONField(default=dict)),
                ('recognition', models.JSONField(default=dict)),
                ('content_type', models.CharField(max_length=100)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('cleanup_pending', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='uploaditem',
            name='documents_item_result_document',
        ),
        migrations.RemoveConstraint(
            model_name='uploaditem',
            name='documents_item_error_code_consistent',
        ),
        migrations.AddField(
            model_name='uploaditem',
            name='validity',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='uploaditem',
            name='status',
            field=models.CharField(choices=[('PENDING', '待上传'), ('UPLOADING', '上传中'), ('UPLOAD_FAILED', '上传失败'), ('VALIDATING', '有效性识别'), ('REJECTED', '拒收'), ('CREATED', '处理中'), ('EXACT_DUPLICATE', '已存在')], default='PENDING', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='uploaditem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('document__isnull', True), ('status__in', ['PENDING', 'UPLOADING', 'UPLOAD_FAILED', 'VALIDATING', 'REJECTED'])), models.Q(('document__isnull', False), ('status__in', ['CREATED', 'EXACT_DUPLICATE'])), _connector='OR'), name='documents_item_result_document'),
        ),
        migrations.AddConstraint(
            model_name='uploaditem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['UPLOAD_FAILED', 'REJECTED']), models.Q(('error_code', ''), _negated=True)), models.Q(('status__in', ['PENDING', 'UPLOADING', 'VALIDATING', 'CREATED', 'EXACT_DUPLICATE']), ('error_code', '')), _connector='OR'), name='documents_item_error_code_consistent'),
        ),
        migrations.AddIndex(
            model_name='uploadintake',
            index=models.Index(fields=['state', 'next_attempt_at'], name='documents_intake_due'),
        ),
    ]
