# Generated by Django 5.2.17 on 2026-09-17 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_uploadintake_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadintake',
            name='access_revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadintake',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_intakes', to=settings.AUTH_USER_MODEL),
        ),
    ]
