# Generated by Django 5.2.17 on 2026-09-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_uploadintake_access_revision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadintake',
            name='promotion_key',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
