# Generated by Django 5.2.17 on 2026-09-06 03:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0005_document_recycle_bin'),
        ('processing', '0003_parsingversion_previous_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin', models.CharField(choices=[('AUTOMATIC', '自动候选'), ('MANUAL', '人工补录')], max_length=12)),
                ('category', models.CharField(choices=[('DIAGNOSIS', '诊断'), ('STAGE', '分期'), ('TREATMENT', '治疗'), ('IMAGING', '影像结论'), ('PATHOLOGY', '病理结论')], max_length=16)),
                ('raw_text', models.TextField()),
                ('automatic_content', models.JSONField()),
                ('reading_order', models.PositiveIntegerField(default=0)),
                ('revision_number', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='documents.document')),
                ('document_page', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='facts', to='documents.documentpage')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='processing.sourceevidence')),
                ('parsing_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='processing.parsingversion')),
            ],
        ),
        migrations.CreateModel(
            name='FactExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('EXTRACTED', '已提取候选'), ('NO_CANDIDATES', '未提取到明确事实'), ('FAILED', '候选提取失败')], max_length=20)),
                ('extractor_version', models.CharField(max_length=40)),
                ('candidate_count', models.PositiveIntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parsing_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fact_extraction', to='processing.parsingversion')),
            ],
        ),
        migrations.CreateModel(
            name='FactRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('action', models.CharField(max_length=16)),
                ('before', models.JSONField()),
                ('after', models.JSONField()),
                ('checked_original', models.BooleanField(default=False)),
                ('source', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='facts.fact')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='fact',
            index=models.Index(fields=['document', 'category'], name='facts_document_category'),
        ),
        migrations.AddConstraint(
            model_name='factrevision',
            constraint=models.UniqueConstraint(fields=('fact', 'sequence'), name='facts_revision_sequence'),
        ),
    ]
