# Generated by Django 5.2.17 on 2026-09-07 17:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_processingrun_access_revision_and_more'),
        ('facts', '0001_initial'),
        ('processing', '0004_ocr_layout_geometry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalReportRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('action', models.CharField(max_length=20)),
                ('before', models.JSONField()),
                ('after', models.JSONField()),
                ('field_revisions', models.JSONField(default=list)),
                ('source_token', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalReportSpan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('start_offset', models.PositiveIntegerField(blank=True, null=True)),
                ('end_offset', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_text', models.TextField(blank=True)),
                ('boundary_basis', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['ordinal'],
            },
        ),
        migrations.CreateModel(
            name='FactSourceFragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('source_kind', models.CharField(choices=[('OCR', '原始OCR片段'), ('MANUAL', '人工原件转录')], max_length=20)),
                ('start_offset', models.PositiveIntegerField(blank=True, null=True)),
                ('end_offset', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_text', models.TextField()),
                ('polygon', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['ordinal'],
            },
        ),
        migrations.AddField(
            model_name='fact',
            name='entity_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fact',
            name='field_key',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='fact',
            name='representation',
            field=models.CharField(choices=[('EXCERPT', '原文摘录'), ('FIELD', '结构化字段')], default='EXCERPT', max_length=8),
        ),
        migrations.AddField(
            model_name='fact',
            name='schema_version',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.CreateModel(
            name='ClinicalExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extractor_version', models.CharField(max_length=40)),
                ('schema_version', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=20)),
                ('report_count', models.PositiveIntegerField(default=0)),
                ('field_count', models.PositiveIntegerField(default=0)),
                ('unparsed_page_count', models.PositiveIntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=64)),
                ('limitations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parsing_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_extraction', to='processing.parsingversion')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin', models.CharField(choices=[('AUTOMATIC', '自动分段'), ('MANUAL', '人工分段')], max_length=12)),
                ('routing_kind', models.CharField(default='IMAGING', max_length=20)),
                ('ordinal', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=256)),
                ('segmenter_version', models.CharField(max_length=40)),
                ('schema_version', models.CharField(max_length=40)),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('lifecycle_revision', models.PositiveIntegerField()),
                ('boundary_state', models.CharField(default='CLEAR', max_length=16)),
                ('limitations', models.JSONField(blank=True, default=list)),
                ('revision_number', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_reports', to='documents.document')),
                ('parsing_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_reports', to='processing.parsingversion')),
            ],
            options={
                'ordering': ['document_id', 'ordinal', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='fact',
            name='clinical_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='facts.clinicalreport'),
        ),
        migrations.AddConstraint(
            model_name='fact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('clinical_report__isnull', True), ('entity_key', ''), ('field_key', ''), ('representation', 'EXCERPT'), ('schema_version', '')), models.Q(('clinical_report__isnull', False), ('representation', 'FIELD'), models.Q(('field_key', ''), _negated=True), models.Q(('entity_key', ''), _negated=True), models.Q(('schema_version', ''), _negated=True)), _connector='OR'), name='facts_representation_identity'),
        ),
        migrations.AddField(
            model_name='clinicalreportrevision',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicalreportrevision',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='facts.clinicalreport'),
        ),
        migrations.AddField(
            model_name='clinicalreportspan',
            name='document_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='documents.documentpage'),
        ),
        migrations.AddField(
            model_name='clinicalreportspan',
            name='ocr_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='processing.ocrblock'),
        ),
        migrations.AddField(
            model_name='clinicalreportspan',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spans', to='facts.clinicalreport'),
        ),
        migrations.AddField(
            model_name='factsourcefragment',
            name='document_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='documents.documentpage'),
        ),
        migrations.AddField(
            model_name='factsourcefragment',
            name='evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='processing.sourceevidence'),
        ),
        migrations.AddField(
            model_name='factsourcefragment',
            name='fact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_fragments', to='facts.fact'),
        ),
        migrations.AddField(
            model_name='factsourcefragment',
            name='ocr_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='processing.ocrblock'),
        ),
        migrations.AddIndex(
            model_name='clinicalreport',
            index=models.Index(fields=['document', 'parsing_version'], name='facts_report_version'),
        ),
        migrations.AddConstraint(
            model_name='clinicalreportrevision',
            constraint=models.UniqueConstraint(fields=('report', 'sequence'), name='facts_report_revision_order'),
        ),
        migrations.AddConstraint(
            model_name='clinicalreportspan',
            constraint=models.UniqueConstraint(fields=('report', 'ordinal'), name='facts_report_span_order'),
        ),
        migrations.AddConstraint(
            model_name='factsourcefragment',
            constraint=models.UniqueConstraint(fields=('fact', 'ordinal'), name='facts_fragment_order'),
        ),
    ]
