# Generated by Django 5.2.17 on 2026-09-08 05:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_document_material_override_and_more'),
        ('facts', '0002_clinicalreportrevision_clinicalreportspan_and_more'),
        ('processing', '0005_materialdecision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fact',
            constraint=models.UniqueConstraint(condition=models.Q(('field_key__in', ['specimen.identity', 'assay.identity', 'ihc.marker']), ('representation', 'FIELD')), fields=('clinical_report', 'entity_key', 'field_key'), name='facts_context_anchor_unique'),
        ),
    ]
