# Generated by Django 5.2.17 on 2026-09-08 09:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0002_clinicalreportrevision_clinicalreportspan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LateralityScopeBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_parent_id', models.UUIDField()),
                ('scope_kind', models.CharField(choices=[('NAMED_MEMBERS_ONLY', '仅限列明部位'), ('WHOLE_ENTITY', '完整部位组')], max_length=24)),
                ('origin', models.CharField(choices=[('AUTOMATIC', '自动来源证明'), ('MANUAL', '人工核对来源')], max_length=12)),
                ('rule_version', models.CharField(max_length=48)),
                ('members', models.JSONField()),
                ('parent_snapshot', models.JSONField()),
                ('original_created_by_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='laterality_scope_binding', to='facts.fact')),
                ('parent_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laterality_dependants', to='facts.fact')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LateralityScopeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_key', models.CharField(max_length=20)),
                ('ordinal', models.PositiveIntegerField()),
                ('original_child_fragment_id', models.PositiveBigIntegerField()),
                ('original_parent_fragment_id', models.PositiveBigIntegerField()),
                ('page_id_at_creation', models.UUIDField()),
                ('block_id_at_creation', models.UUIDField(blank=True, null=True)),
                ('source_kind', models.CharField(choices=[('OCR', '原始字符范围'), ('MANUAL_PAGE', '人工原件页核对')], max_length=16)),
                ('start_offset', models.PositiveIntegerField(blank=True, null=True)),
                ('end_offset', models.PositiveIntegerField(blank=True, null=True)),
                ('reading_order', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_text', models.TextField()),
                ('polygon', models.JSONField(blank=True, null=True)),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='facts.lateralityscopebinding')),
                ('child_fragment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laterality_child_ranges', to='facts.factsourcefragment')),
                ('parent_fragment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laterality_parent_ranges', to='facts.factsourcefragment')),
            ],
            options={
                'ordering': ['ordinal'],
                'constraints': [models.UniqueConstraint(fields=('binding', 'ordinal'), name='facts_side_range_order')],
            },
        ),
    ]
