# Generated by Django 5.2.17 on 2026-09-10 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_document_material_override_and_more'),
        ('facts', '0003_pathology_context_anchors'),
        ('processing', '0005_materialdecision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fact',
            name='facts_context_anchor_unique',
        ),
        migrations.AlterField(
            model_name='fact',
            name='category',
            field=models.CharField(choices=[('DIAGNOSIS', '诊断'), ('STAGE', '分期'), ('TREATMENT', '治疗'), ('IMAGING', '影像结论'), ('PATHOLOGY', '病理结论'), ('MOLECULAR', '分子/基因结论')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='fact',
            constraint=models.UniqueConstraint(condition=models.Q(('field_key__in', ['specimen.identity', 'assay.identity', 'ihc.marker', 'variant.identity', 'drug_evidence.drugs']), ('representation', 'FIELD')), fields=('clinical_report', 'entity_key', 'field_key'), name='facts_context_anchor_unique'),
        ),
    ]
