# Generated by Django 5.2.17 on 2026-09-08 10:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_document_material_override_and_more'),
        ('facts', '0003_laterality_scope'),
        ('patients', '0006_patientshare_sharesource_shareviewergrant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LateralityScopeOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('ADD', '补录范围'), ('REPLACE', '替换范围'), ('ATTEST', '核对完整范围'), ('UNDO', '撤销范围操作')], max_length=12)),
                ('original_old_id', models.UUIDField(blank=True, null=True)),
                ('original_new_id', models.UUIDField()),
                ('original_author_id', models.UUIDField()),
                ('before_state', models.JSONField()),
                ('after_guard', models.JSONField()),
                ('original_reverses_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
                ('new_fact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scope_creations', to='facts.fact')),
                ('old_fact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scope_retirements', to='facts.fact')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('reverses', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal', to='facts.lateralityscopeoperation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LateralityScopeOperationRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_revision_id', models.UUIDField()),
                ('ordinal', models.PositiveIntegerField()),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_links', to='facts.lateralityscopeoperation')),
                ('revision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facts.factrevision')),
            ],
            options={
                'ordering': ['ordinal'],
                'constraints': [models.UniqueConstraint(fields=('operation', 'ordinal'), name='facts_scope_operation_order')],
            },
        ),
    ]
