# Generated by Django 5.2.17 on 2026-09-06 04:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0005_document_recycle_bin'),
        ('patients', '0002_patientpreference_productfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_digest', models.CharField(max_length=64)),
                ('snapshot', models.JSONField(default=dict)),
                ('snapshot_digest', models.CharField(max_length=64)),
                ('options', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PREVIEW', '待确认'), ('QUEUED', '等待生成'), ('GENERATING', '生成中'), ('READY', '可下载'), ('FAILED', '生成失败'), ('CANCELLED', '已取消'), ('INVALIDATED', '内容已失效'), ('EXPIRED', '已过期')], default='PREVIEW', max_length=16)),
                ('generation', models.PositiveIntegerField(default=0)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('object_key', models.CharField(blank=True, max_length=512)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('byte_size', models.PositiveBigIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('failures', models.JSONField(default=list)),
                ('cleanup_pending', models.BooleanField(default=False)),
                ('cleanup_retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ExportAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generation', models.PositiveIntegerField()),
                ('object_key', models.CharField(max_length=512, unique=True)),
                ('staging_key', models.CharField(max_length=512, unique=True)),
                ('cleaned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exports.exportjob')),
            ],
        ),
        migrations.CreateModel(
            name='ExportSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_bindings', to='documents.document')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_bindings', to='exports.exportjob')),
            ],
        ),
        migrations.AddIndex(
            model_name='exportjob',
            index=models.Index(fields=['status', 'expires_at'], name='exports_status_expiry'),
        ),
        migrations.AddIndex(
            model_name='exportjob',
            index=models.Index(fields=['cleanup_pending', 'cleanup_retry_at'], name='exports_cleanup_due'),
        ),
        migrations.AddConstraint(
            model_name='exportjob',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'READY'), _negated=True), models.Q(('completed_at__isnull', False), models.Q(('object_key', ''), _negated=True), models.Q(('sha256', ''), _negated=True), ('byte_size__gt', 0)), _connector='OR'), name='exports_ready_has_file'),
        ),
        migrations.AddConstraint(
            model_name='exportattempt',
            constraint=models.UniqueConstraint(fields=('job', 'generation'), name='exports_attempt_generation'),
        ),
        migrations.AddConstraint(
            model_name='exportsource',
            constraint=models.UniqueConstraint(fields=('job', 'document'), name='exports_source_unique'),
        ),
    ]
