# Generated by Django 5.2.17 on 2026-09-07 20:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0008_document_material_override_and_more'),
        ('facts', '0001_initial'),
        ('labs', '0004_alter_labobservation_raw_value_and_more'),
        ('patients', '0006_patientshare_sharesource_shareviewergrant_and_more'),
        ('processing', '0005_materialdecision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentDerivationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_version', models.CharField(max_length=64)),
                ('input_fingerprint', models.CharField(max_length=64)),
                ('source_manifest_hash', models.CharField(max_length=64)),
                ('access_revision', models.PositiveIntegerField()),
                ('result_counts', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin', models.CharField(choices=[('AUTOMATIC', '原文自动提议'), ('USER', '本人补记')], max_length=12)),
                ('source_key', models.CharField(max_length=80)),
                ('initial_content', models.JSONField()),
                ('current_content', models.JSONField()),
                ('revision_number', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('derivation_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='treatments.treatmentderivationrun')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin', models.CharField(choices=[('AUTOMATIC', '原文自动提议'), ('USER', '本人补记')], max_length=12)),
                ('source_key', models.CharField(max_length=80)),
                ('initial_content', models.JSONField()),
                ('current_content', models.JSONField()),
                ('revision_number', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule_version', models.CharField(blank=True, max_length=64)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='CycleEventLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=16)),
                ('source_token', models.CharField(max_length=64)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_links', to='treatments.treatmentcycle')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_links', to='treatments.treatmentevent')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_token', models.CharField(max_length=64)),
                ('source_revision', models.PositiveIntegerField(default=0)),
                ('lifecycle_revision', models.PositiveIntegerField(default=0)),
                ('material_revision', models.PositiveIntegerField(default=0)),
                ('start_offset', models.PositiveIntegerField()),
                ('end_offset', models.PositiveIntegerField()),
                ('raw_text', models.TextField()),
                ('source', models.JSONField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_evidence', to='documents.document')),
                ('document_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documentpage')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='treatments.treatmentevent')),
                ('fact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facts.fact')),
                ('parsing_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processing.parsingversion')),
                ('source_evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processing.sourceevidence')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentRegimen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin', models.CharField(choices=[('AUTOMATIC', '原文自动提议'), ('USER', '本人补记')], max_length=12)),
                ('source_key', models.CharField(max_length=80)),
                ('initial_content', models.JSONField()),
                ('current_content', models.JSONField()),
                ('revision_number', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('normalized_key', models.CharField(max_length=64)),
                ('episode_key', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.AddField(
            model_name='treatmentcycle',
            name='regimen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='treatments.treatmentregimen'),
        ),
        migrations.CreateModel(
            name='TreatmentRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_id', models.UUIDField()),
                ('request_digest', models.CharField(max_length=64)),
                ('sequence', models.PositiveIntegerField()),
                ('action', models.CharField(max_length=16)),
                ('before', models.JSONField()),
                ('after', models.JSONField()),
                ('checked_original', models.BooleanField(default=False)),
                ('source_tokens', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='treatments.treatmentcycle')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='treatments.treatmentevent')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('regimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='treatments.treatmentregimen')),
            ],
            options={
                'ordering': ['sequence', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CycleRecordLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin', models.CharField(choices=[('AUTOMATIC', '原文自动提议'), ('USER', '本人补记')], max_length=12)),
                ('source_token', models.CharField(max_length=64)),
                ('assigned', models.BooleanField(default=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
                ('observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labs.labobservation')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_links', to='treatments.treatmentcycle')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('document__isnull', False), ('observation__isnull', True)), models.Q(('document__isnull', True), ('observation__isnull', False)), _connector='OR'), name='treatment_record_one_source')],
            },
        ),
        migrations.CreateModel(
            name='CycleLineage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_id', models.UUIDField()),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successors', to='treatments.treatmentcycle')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessors', to='treatments.treatmentcycle')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('predecessor', 'successor'), name='treatment_lineage_unique'), models.CheckConstraint(condition=models.Q(('predecessor', models.F('successor')), _negated=True), name='treatment_lineage_not_self')],
            },
        ),
        migrations.AddConstraint(
            model_name='treatmentderivationrun',
            constraint=models.UniqueConstraint(fields=('patient', 'rule_version', 'input_fingerprint'), name='treatment_run_input_unique'),
        ),
        migrations.AddIndex(
            model_name='treatmentevent',
            index=models.Index(fields=['patient', 'created_at'], name='treatment_event_patient'),
        ),
        migrations.AddConstraint(
            model_name='treatmentevent',
            constraint=models.UniqueConstraint(fields=('patient', 'source_key'), name='treatment_event_source_unique'),
        ),
        migrations.AddConstraint(
            model_name='cycleeventlink',
            constraint=models.UniqueConstraint(fields=('cycle', 'event', 'role'), name='treatment_cycle_event_unique'),
        ),
        migrations.AddConstraint(
            model_name='treatmentevidence',
            constraint=models.CheckConstraint(condition=models.Q(('end_offset__gt', models.F('start_offset'))), name='treatment_evidence_span'),
        ),
        migrations.AddConstraint(
            model_name='treatmentevidence',
            constraint=models.CheckConstraint(condition=models.Q(('fact__isnull', False), ('source_evidence__isnull', False), _connector='OR'), name='treatment_evidence_source'),
        ),
        migrations.AddConstraint(
            model_name='treatmentregimen',
            constraint=models.UniqueConstraint(fields=('patient', 'source_key'), name='treatment_regimen_src_unique'),
        ),
        migrations.AddConstraint(
            model_name='treatmentcycle',
            constraint=models.UniqueConstraint(fields=('patient', 'source_key'), name='treatment_cycle_source_unique'),
        ),
        migrations.AddIndex(
            model_name='treatmentrevision',
            index=models.Index(fields=['patient', 'operation_id'], name='treatment_revision_operation'),
        ),
        migrations.AddConstraint(
            model_name='treatmentrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cycle__isnull', True), ('event__isnull', False), ('regimen__isnull', True)), models.Q(('cycle__isnull', True), ('event__isnull', True), ('regimen__isnull', False)), models.Q(('cycle__isnull', False), ('event__isnull', True), ('regimen__isnull', True)), _connector='OR'), name='treatment_revision_one_target'),
        ),
        migrations.AddConstraint(
            model_name='treatmentrevision',
            constraint=models.UniqueConstraint(fields=('event', 'sequence'), name='treatment_rev_event_seq'),
        ),
        migrations.AddConstraint(
            model_name='treatmentrevision',
            constraint=models.UniqueConstraint(fields=('regimen', 'sequence'), name='treatment_rev_regimen_seq'),
        ),
        migrations.AddConstraint(
            model_name='treatmentrevision',
            constraint=models.UniqueConstraint(fields=('cycle', 'sequence'), name='treatment_rev_cycle_seq'),
        ),
    ]
