# Generated by Django 5.2.17 on 2026-09-07 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_document_material_override_and_more'),
        ('facts', '0002_clinicalreportrevision_clinicalreportspan_and_more'),
        ('labs', '0004_alter_labobservation_raw_value_and_more'),
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cyclerecordlink',
            name='treatment_record_one_source',
        ),
        migrations.AddField(
            model_name='cyclerecordlink',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facts.clinicalreport'),
        ),
        migrations.AddField(
            model_name='treatmentregimen',
            name='events',
            field=models.ManyToManyField(related_name='regimen_groups', to='treatments.treatmentevent'),
        ),
        migrations.AddConstraint(
            model_name='cyclerecordlink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('document__isnull', False), ('observation__isnull', True), ('report__isnull', True)), models.Q(('document__isnull', True), ('observation__isnull', False), ('report__isnull', True)), models.Q(('document__isnull', True), ('observation__isnull', True), ('report__isnull', False)), _connector='OR'), name='treatment_record_one_source'),
        ),
    ]
