# Generated by Django 5.2.17 on 2026-09-07 21:10

import uuid
from django.conf import settings
from django.db import migrations, models


def separate_existing_operations(apps, schema_editor):
    # AddField's callable default may be evaluated once for a whole table.
    # Existing runs therefore receive independent opaque operation identities
    # before the composite uniqueness constraint is installed.
    runs = apps.get_model('treatments', 'TreatmentDerivationRun').objects.using(schema_editor.connection.alias)
    for identity in runs.values_list('pk', flat=True).iterator():
        runs.filter(pk=identity).update(operation_id=uuid.uuid4())


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patientshare_sharesource_shareviewergrant_and_more'),
        ('treatments', '0002_remove_cyclerecordlink_treatment_record_one_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentderivationrun',
            name='operation_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='treatmentderivationrun',
            name='request_digest',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.RunPython(separate_existing_operations, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='treatmentderivationrun',
            constraint=models.UniqueConstraint(fields=('patient', 'operation_id'), name='treatment_run_operation'),
        ),
    ]
