# Generated by Django 5.2.17 on 2026-09-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0003_treatmentderivationrun_operation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyclerecordlink',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
