# Generated by Django 5.2.17 on 2026-09-07 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_document_material_override_and_more'),
        ('exports', '0002_exportjob_access_revision_exportjob_requested_by'),
        ('labs', '0004_alter_labobservation_raw_value_and_more'),
        ('patients', '0006_patientshare_sharesource_shareviewergrant_and_more'),
        ('treatments', '0004_cyclerecordlink_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentExportSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treatments.treatmentcycle')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treatments.treatmentevent')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_sources', to='exports.exportjob')),
                ('observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labs.labobservation')),
                ('regimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treatments.treatmentregimen')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('cycle__isnull', True), ('document__isnull', True), ('event__isnull', False), ('observation__isnull', True), ('regimen__isnull', True)), models.Q(('cycle__isnull', True), ('document__isnull', True), ('event__isnull', True), ('observation__isnull', True), ('regimen__isnull', False)), models.Q(('cycle__isnull', False), ('document__isnull', True), ('event__isnull', True), ('observation__isnull', True), ('regimen__isnull', True)), models.Q(('cycle__isnull', True), ('document__isnull', False), ('event__isnull', True), ('observation__isnull', True), ('regimen__isnull', True)), models.Q(('cycle__isnull', True), ('document__isnull', True), ('event__isnull', True), ('observation__isnull', False), ('regimen__isnull', True)), _connector='OR'), name='treatment_export_one_source'), models.UniqueConstraint(fields=('job', 'event'), name='treatment_export_event_unique'), models.UniqueConstraint(fields=('job', 'regimen'), name='treatment_export_regimen_unique'), models.UniqueConstraint(fields=('job', 'cycle'), name='treatment_export_cycle_unique'), models.UniqueConstraint(fields=('job', 'document'), name='treatment_export_document_unique'), models.UniqueConstraint(fields=('job', 'observation'), name='treatment_export_observation_unique')],
            },
        ),
        migrations.CreateModel(
            name='TreatmentShareSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treatments.treatmentcycle')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treatments.treatmentevent')),
                ('observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labs.labobservation')),
                ('regimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treatments.treatmentregimen')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_sources', to='patients.patientshare')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('cycle__isnull', True), ('document__isnull', True), ('event__isnull', False), ('observation__isnull', True), ('regimen__isnull', True)), models.Q(('cycle__isnull', True), ('document__isnull', True), ('event__isnull', True), ('observation__isnull', True), ('regimen__isnull', False)), models.Q(('cycle__isnull', False), ('document__isnull', True), ('event__isnull', True), ('observation__isnull', True), ('regimen__isnull', True)), models.Q(('cycle__isnull', True), ('document__isnull', False), ('event__isnull', True), ('observation__isnull', True), ('regimen__isnull', True)), models.Q(('cycle__isnull', True), ('document__isnull', True), ('event__isnull', True), ('observation__isnull', False), ('regimen__isnull', True)), _connector='OR'), name='treatment_share_one_source'), models.UniqueConstraint(fields=('share', 'event'), name='treatment_share_event_unique'), models.UniqueConstraint(fields=('share', 'regimen'), name='treatment_share_regimen_unique'), models.UniqueConstraint(fields=('share', 'cycle'), name='treatment_share_cycle_unique'), models.UniqueConstraint(fields=('share', 'document'), name='treatment_share_document_unique'), models.UniqueConstraint(fields=('share', 'observation'), name='treatment_share_observation_unique')],
            },
        ),
    ]
