# Generated by Django 5.2.17 on 2026-08-30 17:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_processingrun_lease_token'),
        ('processing', '0002_documentsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reading_order', models.PositiveIntegerField()),
                ('raw_name', models.CharField(max_length=256)),
                ('standard_code', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Indicator codes must be stable uppercase identifiers.', regex='^[A-Z][A-Z0-9_]{2,63}$')])),
                ('standard_name', models.CharField(max_length=160)),
                ('raw_value', models.CharField(max_length=256)),
                ('result_type', models.CharField(choices=[('NUMERIC', 'Numeric'), ('COMPARATOR', 'Comparator'), ('QUALITATIVE', 'Qualitative'), ('SEMI_QUANTITATIVE', 'Semi-quantitative'), ('STATUS', 'Status')], max_length=24)),
                ('raw_unit', models.CharField(blank=True, max_length=64)),
                ('reference_range_raw', models.CharField(blank=True, max_length=512)),
                ('report_flag_raw', models.CharField(blank=True, max_length=32)),
                ('observation_date', models.DateField(blank=True, null=True)),
                ('institution_raw', models.CharField(blank=True, max_length=512)),
                ('method_raw', models.CharField(blank=True, max_length=256)),
                ('capability_level', models.CharField(choices=[('STABLE', 'Stable'), ('EXPLORATORY', 'Exploratory'), ('SEARCH_ONLY', 'Search only')], max_length=20)),
                ('dictionary_version', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Version identifiers must be stable, printable identifiers.', regex='^[A-Za-z0-9][A-Za-z0-9._+-]{0,63}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_page', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lab_observations', to='documents.documentpage')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lab_observations', to='processing.sourceevidence')),
                ('parsing_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_observations', to='processing.parsingversion')),
            ],
            options={
                'indexes': [models.Index(fields=['parsing_version', 'reading_order'], name='labs_version_order'), models.Index(fields=['standard_code', 'observation_date'], name='labs_standard_date'), models.Index(fields=['raw_name'], name='labs_raw_name')],
                'constraints': [models.UniqueConstraint(fields=('parsing_version', 'document_page', 'reading_order'), name='labs_observation_page_order')],
            },
        ),
    ]
