# Generated by Django 5.2.17 on 2026-09-05 18:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
        ('processing', '0002_documentsummary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labobservation',
            options={'permissions': [('review_labobservation', 'Review explicitly assigned laboratory observations')]},
        ),
        migrations.AddField(
            model_name='labobservation',
            name='field_evidence',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='labobservation',
            name='normalization_candidates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='labobservation',
            name='quality_issues',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='labobservation',
            name='quality_rule_version',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='labobservation',
            name='reference_range',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='labobservation',
            name='revision_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='labobservation',
            name='specimen',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.CreateModel(
            name='ObservationRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin', models.CharField(choices=[('USER', '用户修订'), ('REVIEW', '复核结论')], max_length=12)),
                ('action', models.CharField(choices=[('CONFIRM', '与原件一致'), ('REPORT_ERROR', '识别有误'), ('DEFER', '暂不处理'), ('CORRECT', '更正'), ('UNDO', '撤销上次操作')], max_length=16)),
                ('sequence', models.PositiveIntegerField()),
                ('before', models.JSONField()),
                ('after', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='labs.labobservation')),
                ('source_evidence', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='processing.sourceevidence')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='ReviewTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', '待分配'), ('IN_PROGRESS', '处理中'), ('COMPLETED', '已完成'), ('UNABLE', '无法判断'), ('REVOKED', '已撤销')], default='PENDING', max_length=16)),
                ('revision_number', models.PositiveIntegerField(default=0)),
                ('observation_revision', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_lab_reviews', to=settings.AUTH_USER_MODEL)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_tasks', to='labs.labobservation')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_lab_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewTaskEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('action', models.CharField(max_length=24)),
                ('before_status', models.CharField(blank=True, max_length=16)),
                ('after_status', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='labs.observationrevision')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='labs.reviewtask')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddConstraint(
            model_name='observationrevision',
            constraint=models.UniqueConstraint(fields=('observation', 'sequence'), name='labs_revision_sequence'),
        ),
        migrations.AddIndex(
            model_name='reviewtask',
            index=models.Index(fields=['reviewer', 'status', 'created_at'], name='labs_review_queue'),
        ),
        migrations.AddConstraint(
            model_name='reviewtaskevent',
            constraint=models.UniqueConstraint(fields=('task', 'sequence'), name='labs_review_event_sequence'),
        ),
    ]
