# Generated by Django 5.2.17 on 2026-09-05 18:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_alter_labobservation_options_and_more'),
        ('patients', '0002_patientpreference_productfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('PROJECT', '项目/别名'), ('UNIT', '单位')], max_length=12)),
                ('raw_term', models.CharField(max_length=256)),
                ('normalized_key', models.CharField(max_length=64)),
                ('standard_code', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('PENDING', '待审核'), ('ACCEPTED', '已接受'), ('REJECTED', '已拒绝')], default='PENDING', max_length=12)),
                ('definition', models.JSONField(blank=True, default=dict)),
                ('rules', models.JSONField(blank=True, default=list)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rationale', models.TextField(blank=True)),
                ('revision_number', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictionary_candidates', to='patients.patient')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DictionaryCandidateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('decision', models.CharField(max_length=12)),
                ('definition', models.JSONField(default=dict)),
                ('rules', models.JSONField(default=list)),
                ('rationale', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='labs.dictionarycandidate')),
            ],
        ),
        migrations.CreateModel(
            name='DictionaryCandidateSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='labs.dictionarycandidate')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictionary_sources', to='labs.labobservation')),
            ],
        ),
        migrations.AddConstraint(
            model_name='dictionarycandidate',
            constraint=models.UniqueConstraint(fields=('patient', 'normalized_key'), name='labs_candidate_patient_key'),
        ),
        migrations.AddConstraint(
            model_name='dictionarycandidateevent',
            constraint=models.UniqueConstraint(fields=('candidate', 'sequence'), name='labs_candidate_event_seq'),
        ),
        migrations.AddConstraint(
            model_name='dictionarycandidatesource',
            constraint=models.UniqueConstraint(fields=('candidate', 'observation'), name='labs_candidate_source'),
        ),
    ]
