# Generated by Django 5.2.17 on 2026-09-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_dictionarycandidate_dictionarycandidateevent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labobservation',
            name='raw_value',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='observationrevision',
            name='action',
            field=models.CharField(choices=[('CONFIRM', '与原件一致'), ('REPORT_ERROR', '识别有误'), ('DEFER', '暂不处理'), ('CORRECT', '更正'), ('UNDO', '撤销上次操作'), ('KEEP_REVISION', '核对后沿用人工修订'), ('USE_AUTOMATIC', '核对后采用本次识别')], max_length=16),
        ),
    ]
