# Generated by Django 5.2.17 on 2026-09-17 06:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_document_material_override_and_more'),
        ('labs', '0004_alter_labobservation_raw_value_and_more'),
        ('patients', '0006_patientshare_sharesource_shareviewergrant_and_more'),
        ('processing', '0005_materialdecision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReportUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordinal', models.PositiveIntegerField()),
                ('source_key', models.CharField(max_length=96)),
                ('automatic', models.JSONField()),
                ('revision_number', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_page', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lab_report_units', to='documents.documentpage')),
                ('parsing_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_report_units', to='processing.parsingversion')),
            ],
        ),
        migrations.CreateModel(
            name='LabReportRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('operation_id', models.CharField(max_length=96)),
                ('before', models.JSONField()),
                ('after', models.JSONField()),
                ('source_evidence', models.JSONField()),
                ('rationale', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='labs.labreportunit')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddField(
            model_name='labobservation',
            name='report_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='labs.labreportunit'),
        ),
        migrations.CreateModel(
            name='ReportAssociation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('left_key', models.CharField(max_length=96)),
                ('right_key', models.CharField(max_length=96)),
                ('state', models.CharField(choices=[('AUTO', '自动归并'), ('SAME', '确认同一报告'), ('DIFFERENT', '不同报告'), ('UNDONE', '已撤销'), ('REVIEW', '待核对')], max_length=16)),
                ('evidence_fingerprint', models.CharField(max_length=64)),
                ('basis', models.JSONField(default=dict)),
                ('revision_number', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_report_associations', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ReportAssociationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('operation_id', models.CharField(max_length=96)),
                ('action', models.CharField(max_length=24)),
                ('before_state', models.CharField(blank=True, max_length=16)),
                ('after_state', models.CharField(max_length=16)),
                ('evidence_fingerprint', models.CharField(max_length=64)),
                ('basis', models.JSONField(default=dict)),
                ('rationale', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='labs.reportassociation')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='labreportunit',
            index=models.Index(fields=['source_key'], name='labs_report_source_key'),
        ),
        migrations.AddConstraint(
            model_name='labreportunit',
            constraint=models.UniqueConstraint(fields=('parsing_version', 'document_page', 'ordinal'), name='labs_report_unit_identity'),
        ),
        migrations.AddConstraint(
            model_name='labreportrevision',
            constraint=models.UniqueConstraint(fields=('unit', 'sequence'), name='labs_report_revision_seq'),
        ),
        migrations.AddConstraint(
            model_name='labreportrevision',
            constraint=models.UniqueConstraint(fields=('unit', 'operation_id'), name='labs_report_revision_op'),
        ),
        migrations.AddConstraint(
            model_name='reportassociation',
            constraint=models.UniqueConstraint(fields=('patient', 'left_key', 'right_key'), name='labs_report_pair'),
        ),
        migrations.AddConstraint(
            model_name='reportassociation',
            constraint=models.CheckConstraint(condition=models.Q(('left_key__lt', models.F('right_key'))), name='labs_report_pair_order'),
        ),
        migrations.AddConstraint(
            model_name='reportassociationevent',
            constraint=models.UniqueConstraint(fields=('association', 'sequence'), name='labs_report_event_seq'),
        ),
        migrations.AddConstraint(
            model_name='reportassociationevent',
            constraint=models.UniqueConstraint(fields=('association', 'operation_id'), name='labs_report_event_op'),
        ),
    ]
