# Generated by Django 5.2.17 on 2026-09-17 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0005_labreportunit_labreportrevision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreportrevision',
            name='action',
            field=models.CharField(choices=[('CORRECT', '更正字段'), ('KEEP_REVISION', '核对后沿用人工修订'), ('USE_AUTOMATIC', '核对后采用本次识别')], default='CORRECT', max_length=24),
        ),
        migrations.AddField(
            model_name='labreportrevision',
            name='inherited_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successor_revisions', to='labs.labreportrevision'),
        ),
    ]
