# Generated by Django 5.2.17 on 2026-09-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0006_report_revision_lineage'),
    ]

    operations = [
        migrations.AddField(
            model_name='labobservation',
            name='phase_raw',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='labobservation',
            name='physiological_phase',
            field=models.CharField(blank=True, choices=[('卵泡期', '卵泡期'), ('排卵期', '排卵期'), ('黄体期', '黄体期'), ('绝经期', '绝经期')], max_length=16),
        ),
    ]
