# Generated by Django 5.2.17 on 2026-09-28 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0008_lab_confirmation_batch'),
        ('patients', '0007_patient_demographics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReportReviewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.UUIDField()),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('report_key', models.CharField(max_length=96)),
                ('action', models.CharField(choices=[('SAVE', '保存'), ('CONFIRM', '确认')], max_length=8)),
                ('basis', models.JSONField()),
                ('final_fingerprint', models.CharField(max_length=64)),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_report_reviews', to='patients.patient')),
            ],
            options={
                'indexes': [models.Index(fields=['patient', 'report_key', '-created_at'], name='labs_report_review_latest')],
                'constraints': [models.UniqueConstraint(fields=('patient', 'author', 'operation_id'), name='labs_report_review_op')],
            },
        ),
    ]
