# Generated by Django 5.2.17 on 2026-09-28 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_uploadintake_promotion_key'),
        ('labs', '0010_observation_exclusion_actions'),
        ('processing', '0006_manual_lab_provenance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='labobservation',
            name='manual_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_lab_observations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labobservation',
            name='manual_identity',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='labobservation',
            constraint=models.UniqueConstraint(condition=models.Q(('manual_identity__isnull', False)), fields=('parsing_version', 'manual_identity'), name='labs_manual_identity_version'),
        ),
    ]
