# Generated by Django 5.2.17 on 2026-09-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0011_manual_lab_provenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='labobservation',
            name='manual_conflict',
            field=models.CharField(blank=True, choices=[('VALUE', '结果冲突'), ('SOURCE', '报告区域冲突')], max_length=8),
        ),
    ]
