# Generated by Django 5.2.17 on 2026-08-31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("actor_hash", models.CharField(max_length=64)),
                ("action", models.CharField(max_length=64)),
                ("target_hash", models.CharField(max_length=64)),
                ("result", models.CharField(max_length=16)),
                ("reason_code", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(fields=["action", "-created_at"], name="operations_audit_recent"),
        ),
    ]
