# Generated by Django 5.2.17 on 2026-08-31

import uuid
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeletionTombstone",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[("ACCOUNT", "Account"), ("DOCUMENT", "Document")],
                        max_length=12,
                    ),
                ),
                ("target_hash", models.CharField(max_length=64)),
                ("requested_at", models.DateTimeField(default=timezone.now)),
                ("signature", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="deletiontombstone",
            constraint=models.UniqueConstraint(
                fields=("kind", "target_hash"),
                name="operations_unique_tombstone",
            ),
        ),
        migrations.AddIndex(
            model_name="deletiontombstone",
            index=models.Index(fields=["kind", "created_at"], name="operations_tombstone_export"),
        ),
    ]
