# Generated by Django 5.2.17 on 2026-08-31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_accountsession"),
        ("operations", "0002_deletiontombstone"),
        ("patients", "0002_patientpreference_productfeedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="DictionaryRelease",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version", models.CharField(max_length=64, unique=True)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("artifact_name", models.CharField(max_length=128)),
                ("indicator_count", models.PositiveSmallIntegerField()),
                ("active", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="OperationalMetricSeries",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=80)),
                ("label_key", models.CharField(max_length=512)),
                ("labels", models.JSONField(default=dict)),
                ("value_sum", models.FloatField(default=0)),
                ("sample_count", models.PositiveBigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SupportAccessGrant",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("reason_code", models.CharField(max_length=64)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_access_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_access_grants",
                        to="patients.patient",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="dictionaryrelease",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("active",),
                name="operations_one_active_dictionary",
            ),
        ),
        migrations.AddIndex(
            model_name="dictionaryrelease",
            index=models.Index(fields=["active", "-published_at"], name="operations_dictionary_active"),
        ),
        migrations.AddConstraint(
            model_name="operationalmetricseries",
            constraint=models.UniqueConstraint(
                fields=("name", "label_key"),
                name="operations_unique_metric_series",
            ),
        ),
        migrations.AddIndex(
            model_name="supportaccessgrant",
            index=models.Index(
                fields=["operator", "patient", "expires_at"],
                name="operations_support_grant",
            ),
        ),
    ]
