# Generated by Django 5.2.17 on 2026-09-05 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_operational_controls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryPublicationLock',
            fields=[
                ('key', models.CharField(default='dictionary', max_length=16, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='dictionaryrelease',
            name='diff',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dictionaryrelease',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dictionaryrelease',
            name='previous_release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.dictionaryrelease'),
        ),
        migrations.AddField(
            model_name='dictionaryrelease',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dictionaryrelease',
            name='regression_report',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dictionaryrelease',
            name='rules',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
