# Generated by Django 5.2.17 on 2026-09-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_dictionarypublicationlock_dictionaryrelease_diff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionaryrelease',
            name='candidate_reviews',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='dictionaryrelease',
            name='release_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='dictionaryrelease',
            name='rules_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
