# Generated by Django 5.2.17 on 2026-09-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_dictionaryevaluationevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletiontombstone',
            name='kind',
            field=models.CharField(choices=[('ACCOUNT', 'Account'), ('DOCUMENT', 'Document'), ('PATIENT', 'Patient')], max_length=12),
        ),
    ]
