# Generated by Django 5.2.17 on 2026-09-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_alter_deletiontombstone_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='actor_kind',
            field=models.CharField(default='legacy', max_length=12),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='patient_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='request_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='resource_type',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='route_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['patient_hash', '-created_at'], name='operations_patient_audit'),
        ),
    ]
