# Generated by Django 5.2.17 on 2026-09-07 14:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patientpreference_productfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeedback', name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PatientDeletionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ADMIN', '管理员'), ('EDITOR', '协作者'), ('VIEWER', '只读成员')], max_length=12)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientpreference',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientpreference',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_rows', to='patients.patient'),
        ),
        migrations.AddConstraint(
            model_name='patientpreference',
            constraint=models.UniqueConstraint(fields=('patient', 'account'), name='patients_preference_member_unique'),
        ),
        migrations.AddField(
            model_name='patientdeletionjob',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_job', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='patientdeletionjob',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientmembership',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientmembership',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='patients.patient'),
        ),
        migrations.AddConstraint(
            model_name='patientmembership',
            constraint=models.UniqueConstraint(fields=('patient', 'account'), name='patients_member_unique'),
        ),
    ]
