# Generated by Django 5.2.17 on 2026-09-07 16:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_migrate_family_ownership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creator_revision', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('ADMIN', '管理员'), ('EDITOR', '协作者'), ('VIEWER', '只读成员')], max_length=12)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('recipient_phone_hash', models.CharField(blank=True, max_length=64)),
                ('recipient_account_id', models.UUIDField(blank=True, null=True)),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_patient_invitations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patient_invitations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='patients.patient')),
            ],
            options={
                'indexes': [models.Index(fields=['patient', '-created_at'], name='patients_invitation_recent')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('recipient_account_id__isnull', True), models.Q(('recipient_phone_hash', ''), _negated=True)), models.Q(('recipient_account_id__isnull', False), ('recipient_phone_hash', '')), _connector='OR'), name='patients_invitation_recipient')],
            },
        ),
    ]
