# Generated by Django 5.2.17 on 2026-09-07 17:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_processingrun_access_revision_and_more'),
        ('patients', '0005_patientinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creator_revision', models.PositiveIntegerField()),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('scope', models.JSONField(default=dict)),
                ('snapshot', models.JSONField(default=dict)),
                ('snapshot_digest', models.CharField(max_length=64)),
                ('allow_original_download', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('invalidation_reason', models.CharField(blank=True, max_length=32)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patient_shares', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ShareSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_bindings', to='documents.document')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_bindings', to='patients.patientshare')),
            ],
        ),
        migrations.CreateModel(
            name='ShareViewerGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_grants', to=settings.AUTH_USER_MODEL)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer_grants', to='patients.patientshare')),
            ],
        ),
        migrations.AddIndex(
            model_name='patientshare',
            index=models.Index(fields=['patient', '-created_at'], name='patients_share_recent'),
        ),
        migrations.AddConstraint(
            model_name='sharesource',
            constraint=models.UniqueConstraint(fields=('share', 'document'), name='patients_share_source_unique'),
        ),
        migrations.AddConstraint(
            model_name='shareviewergrant',
            constraint=models.UniqueConstraint(fields=('share', 'account', 'session_digest'), name='patients_share_session_unique'),
        ),
    ]
