# Generated by Django 5.2.17 on 2026-09-08 06:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0008_document_material_override_and_more'),
        ('facts', '0002_clinicalreportrevision_clinicalreportspan_and_more'),
        ('patients', '0006_patientshare_sharesource_shareviewergrant_and_more'),
        ('processing', '0005_materialdecision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudImagingScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_revision', models.PositiveIntegerField(default=0)),
                ('operation_id', models.UUIDField(default=uuid.uuid4)),
                ('input_fingerprint', models.CharField(max_length=64)),
                ('rules_version', models.CharField(max_length=64)),
                ('decoder_version', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('QUEUED', '等待扫描'), ('RUNNING', '正在扫描'), ('SUCCEEDED', '扫描完成'), ('FAILED', '扫描未完成'), ('INVALIDATED', '输入或访问已变化')], default='QUEUED', max_length=16)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('page_results', models.JSONField(default=list)),
                ('summary', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_imaging_scans', to='documents.document')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_imaging_scans', to='patients.patient')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CloudImagingEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('OCR', '原始文字'), ('QR', '本地二维码'), ('MANUAL', '人工原页转录')], max_length=8)),
                ('payload', models.TextField(blank=True)),
                ('payload_sha256', models.CharField(max_length=64)),
                ('payload_type', models.CharField(choices=[('URL', '地址候选'), ('UNSUPPORTED', '不支持的内容'), ('UNDECODED', '尚未解码')], max_length=16)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('document_sha256', models.CharField(max_length=64)),
                ('page_width', models.PositiveIntegerField(blank=True, null=True)),
                ('page_height', models.PositiveIntegerField(blank=True, null=True)),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('start_offset', models.PositiveIntegerField(blank=True, null=True)),
                ('end_offset', models.PositiveIntegerField(blank=True, null=True)),
                ('polygon', models.JSONField(blank=True, null=True)),
                ('input_sha256', models.CharField(blank=True, max_length=64)),
                ('render_profile', models.CharField(blank=True, max_length=100)),
                ('decoder_version', models.CharField(blank=True, max_length=64)),
                ('transform', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_imaging_evidence', to='documents.document')),
                ('document_page', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='documents.documentpage')),
                ('ocr_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='processing.ocrblock')),
                ('parsing_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='processing.parsingversion')),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='cloud_imaging.cloudimagingscan')),
            ],
        ),
        migrations.CreateModel(
            name='CloudImagingSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('current_url', models.TextField(blank=True)),
                ('site_label', models.CharField(blank=True, max_length=260)),
                ('status', models.CharField(choices=[('PENDING', '待核对'), ('CONFIRMED', '已核对'), ('EXCLUDED', '已排除'), ('STALE', '来源已变化')], default='PENDING', max_length=12)),
                ('confirmed_fingerprint', models.CharField(blank=True, max_length=64)),
                ('revision_number', models.PositiveIntegerField(default=0)),
                ('operation_id', models.UUIDField(default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_imaging_sources', to='documents.document')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='current_sources', to='cloud_imaging.cloudimagingevidence')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_imaging_sources', to='patients.patient')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloud_imaging_sources', to='facts.clinicalreport')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CloudImagingRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('action', models.CharField(max_length=20)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('source_token', models.CharField(max_length=64)),
                ('request_digest', models.CharField(max_length=64)),
                ('checked_original', models.BooleanField(default=False)),
                ('operation_id', models.UUIDField(default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='revisions', to='cloud_imaging.cloudimagingevidence')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='cloud_imaging.cloudimagingsource')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='cloudimagingscan',
            index=models.Index(fields=['status', 'lease_expires_at'], name='cloud_scan_recovery'),
        ),
        migrations.AddConstraint(
            model_name='cloudimagingscan',
            constraint=models.UniqueConstraint(fields=('patient', 'operation_id'), name='cloud_scan_operation'),
        ),
        migrations.AddConstraint(
            model_name='cloudimagingscan',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['QUEUED', 'RUNNING'])), fields=('document', 'input_fingerprint', 'rules_version', 'decoder_version'), name='cloud_scan_one_pending_input'),
        ),
        migrations.AddConstraint(
            model_name='cloudimagingevidence',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('end_offset__gt', models.F('start_offset')), ('end_offset__isnull', False), ('kind', 'OCR'), ('ocr_block__isnull', False), ('start_offset__isnull', False)), models.Q(('end_offset__isnull', True), ('kind__in', ['QR', 'MANUAL']), ('ocr_block__isnull', True), ('start_offset__isnull', True)), _connector='OR'), name='cloud_evidence_text_identity'),
        ),
        migrations.AddIndex(
            model_name='cloudimagingsource',
            index=models.Index(fields=['patient', 'document', 'status'], name='cloud_source_patient_document'),
        ),
        migrations.AddConstraint(
            model_name='cloudimagingsource',
            constraint=models.UniqueConstraint(fields=('patient', 'operation_id'), name='cloud_source_operation'),
        ),
        migrations.AddConstraint(
            model_name='cloudimagingrevision',
            constraint=models.UniqueConstraint(fields=('source', 'sequence'), name='cloud_revision_sequence'),
        ),
        migrations.AddConstraint(
            model_name='cloudimagingrevision',
            constraint=models.UniqueConstraint(fields=('source', 'operation_id'), name='cloud_revision_operation'),
        ),
    ]
