# Generated by Django 5.2.17 on 2026-09-10 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_imaging', '0001_initial'),
        ('documents', '0008_document_material_override_and_more'),
        ('exports', '0002_exportjob_access_revision_exportjob_requested_by'),
        ('patients', '0006_patientshare_sharesource_shareviewergrant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudExportSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_identity', models.UUIDField()),
                ('evidence_identity', models.UUIDField()),
                ('document_identity', models.UUIDField(db_index=True)),
                ('revision_number', models.PositiveIntegerField()),
                ('source_token', models.CharField(max_length=64)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.document')),
                ('evidence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cloud_imaging.cloudimagingevidence')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_sources', to='exports.exportjob')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cloud_imaging.cloudimagingsource')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('job', 'source_identity'), name='cloud_export_source_identity')],
            },
        ),
        migrations.CreateModel(
            name='CloudShareSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_identity', models.UUIDField()),
                ('evidence_identity', models.UUIDField()),
                ('document_identity', models.UUIDField(db_index=True)),
                ('revision_number', models.PositiveIntegerField()),
                ('source_token', models.CharField(max_length=64)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.document')),
                ('evidence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cloud_imaging.cloudimagingevidence')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_sources', to='patients.patientshare')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cloud_imaging.cloudimagingsource')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('share', 'source_identity'), name='cloud_share_source_identity')],
            },
        ),
    ]
