# Generated by Django 5.2.17 on 2026-09-07 19:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0004_migrate_family_ownership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_key', models.UUIDField()),
                ('creation_fingerprint', models.CharField(max_length=64)),
                ('original_data', models.JSONField()),
                ('current_data', models.JSONField()),
                ('kind', models.CharField(choices=[('WEIGHT', '体重'), ('TEMPERATURE', '体温'), ('SYMPTOM', '症状')], max_length=16)),
                ('measured_at', models.DateTimeField()),
                ('revision_number', models.PositiveIntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_daily_records', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_records', to='patients.patient')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_daily_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-measured_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DailyRecordRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('CORRECT', '更正'), ('DELETE', '删除'), ('UNDO', '撤销')], max_length=16)),
                ('before', models.JSONField()),
                ('after', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='self_records.dailyrecord')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='dailyrecord',
            index=models.Index(fields=['patient', 'deleted_at', '-measured_at'], name='self_records_patient_time'),
        ),
        migrations.AddConstraint(
            model_name='dailyrecord',
            constraint=models.UniqueConstraint(fields=('patient', 'created_by', 'creation_key'), name='self_records_creation_unique'),
        ),
        migrations.AddConstraint(
            model_name='dailyrecordrevision',
            constraint=models.UniqueConstraint(fields=('record', 'sequence'), name='self_records_revision_unique'),
        ),
    ]
