# Generated by Django 5.2.17 on 2026-09-07 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0002_exportjob_access_revision_exportjob_requested_by'),
        ('patients', '0006_patientshare_sharesource_shareviewergrant_and_more'),
        ('self_records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecordExportSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_record_sources', to='exports.exportjob')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_bindings', to='self_records.dailyrecord')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('job', 'record'), name='self_records_export_unique')],
            },
        ),
        migrations.CreateModel(
            name='DailyRecordShareSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_bindings', to='self_records.dailyrecord')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_record_sources', to='patients.patientshare')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('share', 'record'), name='self_records_share_unique')],
            },
        ),
    ]
