# Generated by Django 5.2.17 on 2026-09-08 00:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0008_document_material_override_and_more'),
        ('facts', '0002_clinicalreportrevision_clinicalreportspan_and_more'),
        ('patients', '0006_patientshare_sharesource_shareviewergrant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_number', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_name', models.CharField(max_length=120)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesions', to='patients.patient')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='LesionObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_number', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_report_id', models.UUIDField()),
                ('entity_key', models.CharField(max_length=100)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesion_observations', to='documents.document')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesion_observations', to='patients.patient')),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesion_observations', to='facts.clinicalreport')),
            ],
        ),
        migrations.CreateModel(
            name='LesionMatchProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_number', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_binding', models.JSONField()),
                ('second_binding', models.JSONField()),
                ('rule_version', models.CharField(max_length=64)),
                ('reasons', models.JSONField(default=list)),
                ('blockers', models.JSONField(default=list)),
                ('fingerprint', models.CharField(max_length=64)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesion_proposals', to='patients.patient')),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_proposals', to='lesions.lesionobservation')),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_proposals', to='lesions.lesionobservation')),
            ],
        ),
        migrations.CreateModel(
            name='LesionOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=24)),
                ('checked_original', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesion_operations', to='patients.patient')),
                ('reverses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_by', to='lesions.lesionoperation')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='LesionObservationRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('before', models.JSONField()),
                ('after', models.JSONField()),
                ('lesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observation_revisions', to='lesions.lesion')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='lesions.lesionobservation')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observation_revisions', to='lesions.lesionoperation')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='LesionProposalRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('before', models.JSONField()),
                ('after', models.JSONField()),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_revisions', to='lesions.lesionoperation')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='lesions.lesionmatchproposal')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='LesionRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('before', models.JSONField()),
                ('after', models.JSONField()),
                ('lesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='lesions.lesion')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesion_revisions', to='lesions.lesionoperation')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddConstraint(
            model_name='lesionobservation',
            constraint=models.UniqueConstraint(fields=('original_report_id', 'entity_key'), name='lesions_report_entity_unique'),
        ),
        migrations.AddConstraint(
            model_name='lesionmatchproposal',
            constraint=models.UniqueConstraint(fields=('patient', 'fingerprint'), name='lesions_proposal_unique'),
        ),
        migrations.AddConstraint(
            model_name='lesionobservationrevision',
            constraint=models.UniqueConstraint(fields=('observation', 'sequence'), name='lesions_obs_revision_unique'),
        ),
        migrations.AddConstraint(
            model_name='lesionproposalrevision',
            constraint=models.UniqueConstraint(fields=('proposal', 'sequence'), name='lesions_proposal_revision_unique'),
        ),
        migrations.AddConstraint(
            model_name='lesionrevision',
            constraint=models.UniqueConstraint(fields=('lesion', 'sequence'), name='lesions_name_revision_unique'),
        ),
    ]
