# Generated by Django 5.2.17 on 2026-09-08 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0002_exportjob_access_revision_exportjob_requested_by'),
        ('lesions', '0001_initial'),
        ('patients', '0006_patientshare_sharesource_shareviewergrant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LesionExportSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('LESION', '病灶标识'), ('OBSERVATION', '报告观察')], max_length=12)),
                ('original_id', models.UUIDField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesion_sources', to='exports.exportjob')),
                ('lesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lesions.lesion')),
                ('observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lesions.lesionobservation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('job', 'kind', 'original_id'), name='lesion_export_source_unique')],
            },
        ),
        migrations.CreateModel(
            name='LesionShareSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('LESION', '病灶标识'), ('OBSERVATION', '报告观察')], max_length=12)),
                ('original_id', models.UUIDField()),
                ('lesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lesions.lesion')),
                ('observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lesions.lesionobservation')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesion_sources', to='patients.patientshare')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('share', 'kind', 'original_id'), name='lesion_share_source_unique')],
            },
        ),
    ]
