"""Compile Linux production and test dependency hashes from pyproject.toml."""

import argparse
from pathlib import Path
import subprocess
import tempfile
import tomllib


ROOT = Path(__file__).resolve().parents[1]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--uv", default="uv", help="Path to the uv executable")
    parser.add_argument("--upgrade", action="store_true", help="Resolve new versions within pyproject constraints")
    options = parser.parse_args()
    project = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    common = [options.uv, "pip", "compile", "--python-version", "3.11",
              "--python-platform", "x86_64-unknown-linux-gnu", "--generate-hashes", "--no-header", "--quiet"]
    with tempfile.TemporaryDirectory(prefix="phr-dependency-lock-") as directory:
        temporary = Path(directory)
        production = temporary / "requirements-prod.lock"
        testing = temporary / "requirements-test.lock"
        test_input = temporary / "test.in"
        test_input.write_text("\n".join(project["project"]["optional-dependencies"]["test"]) + "\n", encoding="utf-8")
        constraints = [] if options.upgrade else ["--constraint", str(ROOT / "requirements-prod.lock")]
        test_constraints = [] if options.upgrade else ["--constraint", str(ROOT / "requirements-test.lock")]
        subprocess.run([*common, "pyproject.toml", "--extra", "ocr", *constraints,
                        "--output-file", str(production)], cwd=ROOT, check=True)
        subprocess.run([*common, str(test_input), "--constraint", str(production), *test_constraints,
                        "--output-file", str(testing)], cwd=ROOT, check=True)
        for name, output in (("requirements-prod.lock", production), ("requirements-test.lock", testing)):
            # Avoid embedding machine-specific temporary paths in a committed lock.
            content = output.read_text(encoding="utf-8")
            content = content.replace(str(test_input), "pyproject.toml [test]")
            content = content.replace(str(test_input).replace("\\", "/"), "pyproject.toml [test]")
            content = content.replace(str(production), "requirements-prod.lock")
            content = content.replace(str(production).replace("\\", "/"), "requirements-prod.lock")
            header = "# Generated by tools/update_dependency_locks.py for Python 3.11 / Linux x86_64.\n"
            (ROOT / name).write_text(header + content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
