# Generated by Django 5.2.17 on 2026-08-30 17:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('LAB', '检验报告'), ('IMAGING', '影像报告'), ('PATHOLOGY', '病理报告'), ('DISCHARGE', '出院小结'), ('ORDER', '医嘱/处方'), ('TREATMENT', '治疗记录'), ('OTHER', '其他'), ('UNKNOWN', '未识别')], default='UNKNOWN', max_length=16)),
                ('document_date_raw', models.CharField(blank=True, max_length=256)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('date_precision', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('YEAR', 'Year'), ('MONTH', 'Month'), ('DAY', 'Day')], default='UNKNOWN', max_length=12)),
                ('institution_raw', models.CharField(blank=True, max_length=512)),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parsing_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_summary', to='processing.parsingversion')),
            ],
            options={
                'indexes': [models.Index(fields=['document_type', '-document_date'], name='processing_summary_type_date')],
            },
        ),
    ]
