# Generated by Django 5.2.17 on 2026-09-05 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_documentsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsingversion',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successor_versions', to='processing.parsingversion'),
        ),
    ]
