# Generated by Django 5.2.17 on 2026-09-07 14:41

import apps.processing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0003_parsingversion_previous_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrblock',
            name='layout_polygon',
            field=models.JSONField(blank=True, null=True, validators=[apps.processing.models.validate_normalized_polygon]),
        ),
        migrations.AlterField(
            model_name='ocrblock',
            name='polygon',
            field=models.JSONField(blank=True, null=True, validators=[apps.processing.models.validate_normalized_polygon]),
        ),
    ]
