# Generated by Django 5.2.17 on 2026-09-07 16:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_document_material_override_and_more'),
        ('processing', '0004_ocr_layout_geometry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('KEEP_DOCUMENT', '按资料保留'), ('AUTO', '恢复自动判断')], max_length=16)),
                ('source_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='A lowercase SHA-256 digest is required.', regex='^[0-9a-f]{64}$')])),
                ('automatic_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_decisions', to='documents.document')),
                ('parsing_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_decisions', to='processing.parsingversion')),
                ('processing_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.processingrun')),
            ],
            options={
                'ordering': ['sequence'],
                'constraints': [models.UniqueConstraint(fields=('document', 'sequence'), name='processing_material_sequence'), models.CheckConstraint(condition=models.Q(('sequence__gt', 0)), name='processing_material_positive')],
            },
        ),
    ]
