# Generated by Django 5.2.17 on 2026-09-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0005_materialdecision'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceevidence',
            name='origin',
            field=models.CharField(choices=[('AUTOMATIC', '自动识别'), ('MANUAL', '人工转录')], default='AUTOMATIC', max_length=12),
        ),
    ]
