# Generated by Django 5.2.17 on 2026-09-07 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('patients', '0003_patientdeletionjob_patientmembership_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='pushsubscription',
            name='notify_unique_patient_endpoint',
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='pushsubscription',
            constraint=models.UniqueConstraint(fields=('patient', 'account', 'endpoint_hash'), name='notify_unique_patient_endpoint'),
        ),
        migrations.AddField(
            model_name='notificationreceipt',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationreceipt',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='notifications.tasknotification'),
        ),
        migrations.AddConstraint(
            model_name='notificationreceipt',
            constraint=models.UniqueConstraint(fields=('notification', 'account'), name='notify_receipt_member_unique'),
        ),
    ]
